### ISSUE TITLE
Drop-Down List on Shortcode Builder Showing Behind Modal Window

### ISSUE THREAD

**Issue by davidshq** [surajprgupta/taxonomy-listing#10]
When using the shortcode builder, the dropdown list of fields is populating but it is appearing behind the modal window. See screenshot here:

https://goo.gl/photos/kdhwdg1jvX6my8Qu7

**Comment by surajprgupta** [comment]
can you clear browser cache (ctrl + f5) and recheck, for me it's working fine - 
![image](https://cloud.githubusercontent.com/assets/5558630/24577957/0f3ee2ee-16f5-11e7-82e4-9d60ee0a50ec.png)

**Comment by surajprgupta** [comment]
I have fixed the css for select2 and updated it on philcata.com

**Comment by davidshq** [comment]
The drop-down behind modal issue is fixed, but I'm now seeing a different one. When I select the drop down without selecting a field and then attempt to move focus away from the select drop-down, the drop-down refuses to release focus. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/8009774/24579933/44d4cea0-16cd-11e7-8091-47cc44273ba6.png)

I can't close either of these drop down lists.

**Comment by surajprgupta** [comment]
these issues are not present in local development version, it's there in the live environment because of a plugin (Advanced custom fields pro), it's using a older version of select2 - 3.5.2 and I am using Select2 4.0.3 .
I can't isolate the older version of select2 - http://stackoverflow.com/questions/33962395/select2-multiple-versions-on-same-page-site
I will find a way and let you know...

**Comment by surajprgupta** [comment]
issues regarding select2 are fixed and also changes are synced to philcata.com
