### ISSUE TITLE
Implode Error in template-top-level.php

### ISSUE THREAD

**Issue by davidshq** [surajprgupta/taxonomy-listing#9]
You can view error here:
http://www.philcata.com/offering_category/

Error is:
Warning: implode(): Invalid arguments passed in /home/davemack/public_html/philcata.com/wp-content/plugins/taxonomy-listing-plugin/templates/template-top-level.php on line 30

This is after updating to most recent source code available in repository.

**Comment by surajprgupta** [comment]
Have you re-inserted the shortcode using the shortcode button?

**Comment by davidshq** [comment]
I had not, Trying that now...but can we provide a default value so this error isn't thrown or otherwise handle it?

**Comment by surajprgupta** [comment]
earlier shortcode entered in the editor is like - 
`[scrptz_tdl select_taxonomy="section" term_description="true" post_data="|~'post_excerpt','post_author','post_date'~|" post_meta_fields="offer_description"]`

So, post_meta field is a comma separated link and is processed as an array, but if you replace the shortcode now, it will be like - 
`[scrptz_tdl select_taxonomy="section" term_description="true" post_data="|~'post_excerpt','post_author','post_date'~|" post_meta_fields="|~'offer_description'~|"]`

you can see `post_meta_fields="|~'offer_description'~|"` is different and will be processed as an array when shortcode will be run.

If there were no `post_meta` fields mentioned in the shortcode then no error will appear,

right now the error was showing because it is processed as a string. updating the shortcode will fix the issue, by the way I have updated the shortcode in philcata.com
